DROP TABLE if exists tb_member_detail;

CREATE TABLE `tb_member_detail` (
                                    `mb_id` char(36) DEFAULT NULL COMMENT 'member join id(uuid)',
                                    `mb_mobile` varchar(32) NOT NULL,
                                    `mb_email` varchar(64) NOT NULL,
                                    `mb_homepage` varchar(255) DEFAULT NULL,
                                    `mb_image` varchar(255) DEFAULT NULL,
                                    `mb_gender` char(1) DEFAULT NULL,
                                    `mb_married` bit(1) DEFAULT b'0' COMMENT 'member IsMarried flag(0:not married, 1:married)',
                                    `mb_birthday` date DEFAULT NULL,
                                    `mb_adult` bit(1) DEFAULT NULL,
                                    `mb_zip` char(8) DEFAULT NULL,
                                    `mb_addr1` varchar(255) DEFAULT NULL,
                                    `mb_addr2` varchar(255) DEFAULT NULL,
                                    `mb_addr3` varchar(255) DEFAULT NULL,
                                    `mb_addr_jibeon` varchar(255) DEFAULT NULL,
                                    `mb_latitude` double DEFAULT NULL,
                                    `mb_longitude` double DEFAULT NULL,
                                    `mb_signature` text,
                                    `mb_recommend` varchar(255) DEFAULT NULL,
                                    `mb_today_login` datetime NOT NULL,
                                    `mb_login_ip` varchar(255) DEFAULT NULL,
                                    `mb_ip` varchar(255) DEFAULT NULL,
                                    `mb_leave_date` date DEFAULT NULL,
                                    `mb_intercept_date` date DEFAULT NULL,
                                    `mb_email_certify` datetime  DEFAULT  NULL,
                                    `mb_email_certify2` varchar(255) DEFAULT NULL,
                                    `mb_mobile_certify` datetime  DEFAULT  NULL,
                                    `mb_mobile_certify2` varchar(255) DEFAULT NULL,
                                    `mb_memo` text,
                                    `mb_lost_certify` varchar(255)  NULL,
                                    `mb_mailling` bit(1) DEFAULT NULL,
                                    `mb_sms` bit(1) DEFAULT NULL,
                                    `mb_open` bit(1) DEFAULT NULL,
                                    `mb_open_date` date DEFAULT NULL,
                                    `mb_greeting` text,
                                    `mb_memo_call` varchar(255) DEFAULT NULL,
                                    `mb_memo_cnt` int DEFAULT NULL,
                                    `mb_scrap_cnt` int DEFAULT NULL,
                                    `mb_1` varchar(255) DEFAULT NULL,
                                    `mb_2` varchar(255) DEFAULT NULL,
                                    `mb_3` varchar(255) DEFAULT NULL,
                                    `mb_4` varchar(255) DEFAULT NULL,
                                    `mb_5` varchar(255) DEFAULT NULL,
                                    `mb_6` varchar(255) DEFAULT NULL,
                                    `mb_7` varchar(255) DEFAULT NULL,
                                    `mb_8` varchar(255) DEFAULT NULL,
                                    `mb_9` varchar(255) DEFAULT NULL,
                                    `mb_10` varchar(255) DEFAULT NULL,
                                    UNIQUE KEY `mb_email` (`mb_email`),
                                    UNIQUE KEY `mb_mobile` (`mb_mobile`),
                                    UNIQUE KEY `mb_id` (`mb_id`),
                                    CONSTRAINT `tb_member_detail_ibfk_1` FOREIGN KEY (`mb_id`) REFERENCES `tb_member` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;