SET FOREIGN_KEY_CHECKS=0;

INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AD', 'Andorra, Principality of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AE', 'United Arab Emirates', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AF', 'Afghanistan, Islamic Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AG', 'Antigua and Barbuda', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AI', 'Anguilla', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AL', 'Albania, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AM', 'Armenia, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AN', 'Netherlands Antilles', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AO', 'Angola, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AQ', 'Antarctica (the territory South of 60 deg S)', 'AN');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AR', 'Argentina, Argentine Republic', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AS', 'American Samoa', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AT', 'Austria, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AU', 'Australia, Commonwealth of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AW', 'Aruba', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AX', '?land Islands', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('AZ', 'Azerbaijan, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BA', 'Bosnia and Herzegovina', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BB', 'Barbados', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BD', 'Bangladesh, People''s Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BE', 'Belgium, Kingdom of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BF', 'Burkina Faso', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BG', 'Bulgaria, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BH', 'Bahrain, Kingdom of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BI', 'Burundi, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BJ', 'Benin, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BL', 'Saint Barthelemy', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BM', 'Bermuda', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BN', 'Brunei Darussalam', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BO', 'Bolivia, Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BR', 'Brazil, Federative Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BS', 'Bahamas, Commonwealth of the', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BT', 'Bhutan, Kingdom of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BV', 'Bouvet Island (Bouvetoya)', 'AN');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BW', 'Botswana, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BY', 'Belarus, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('BZ', 'Belize', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CA', 'Canada', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CC', 'Cocos (Keeling) Islands', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CD', 'Congo, Democratic Republic of the', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CF', 'Central African Republic', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CG', 'Congo, Republic of the', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CH', 'Switzerland, Swiss Confederation', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CI', 'Cote d''Ivoire, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CK', 'Cook Islands', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CL', 'Chile, Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CM', 'Cameroon, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CN', 'China, People''s Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CO', 'Colombia, Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CR', 'Costa Rica, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CU', 'Cuba, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CV', 'Cape Verde, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CW', 'Cura?ao', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CX', 'Christmas Island', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CY', 'Cyprus, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('CZ', 'Czech Republic', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('DE', 'Germany, Federal Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('DJ', 'Djibouti, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('DK', 'Denmark, Kingdom of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('DM', 'Dominica, Commonwealth of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('DO', 'Dominican Republic', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('DZ', 'Algeria, People''s Democratic Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('EC', 'Ecuador, Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('EE', 'Estonia, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('EG', 'Egypt, Arab Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('EH', 'Western Sahara', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ER', 'Eritrea, State of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ES', 'Spain, Kingdom of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ET', 'Ethiopia, Federal Democratic Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('FI', 'Finland, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('FJ', 'Fiji, Republic of the Fiji Islands', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('FK', 'Falkland Islands (Malvinas)', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('FM', 'Micronesia, Federated States of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('FO', 'Faroe Islands', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('FR', 'France, French Republic', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GA', 'Gabon, Gabonese Republic', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GB', 'United Kingdom of Great Britain & Northern Ireland', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GD', 'Grenada', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GE', 'Georgia', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GF', 'French Guiana', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GG', 'Guernsey, Bailiwick of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GH', 'Ghana, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GI', 'Gibraltar', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GL', 'Greenland', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GM', 'Gambia, Republic of the', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GN', 'Guinea, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GP', 'Guadeloupe', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GQ', 'Equatorial Guinea, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GR', 'Greece, Hellenic Republic', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'AN');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GT', 'Guatemala, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GU', 'Guam', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GW', 'Guinea-Bissau, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('GY', 'Guyana, Co-operative Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('HK', 'Hong Kong, Special Administrative Region of China', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('HM', 'Heard Island and McDonald Islands', 'AN');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('HN', 'Honduras, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('HR', 'Croatia, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('HT', 'Haiti, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('HU', 'Hungary, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ID', 'Indonesia, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IE', 'Ireland', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IL', 'Israel, State of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IM', 'Isle of Man', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IN', 'India, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IO', 'British Indian Ocean Territory (Chagos Archipelago)', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IQ', 'Iraq, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IR', 'Iran, Islamic Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IS', 'Iceland, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('IT', 'Italy, Italian Republic', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('JE', 'Jersey, Bailiwick of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('JM', 'Jamaica', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('JO', 'Jordan, Hashemite Kingdom of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('JP', 'Japan', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KE', 'Kenya, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KG', 'Kyrgyz Republic', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KH', 'Cambodia, Kingdom of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KI', 'Kiribati, Republic of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KM', 'Comoros, Union of the', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KN', 'Saint Kitts and Nevis, Federation of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KP', 'Korea, Democratic People''s Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KR', 'Korea, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KW', 'Kuwait, State of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KY', 'Cayman Islands', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('KZ', 'Kazakhstan, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LA', 'Lao People''s Democratic Republic', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LB', 'Lebanon, Lebanese Republic', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LC', 'Saint Lucia', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LI', 'Liechtenstein, Principality of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LK', 'Sri Lanka, Democratic Socialist Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LR', 'Liberia, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LS', 'Lesotho, Kingdom of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LT', 'Lithuania, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LU', 'Luxembourg, Grand Duchy of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LV', 'Latvia, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('LY', 'Libyan Arab Jamahiriya', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MA', 'Morocco, Kingdom of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MC', 'Monaco, Principality of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MD', 'Moldova, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ME', 'Montenegro, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MF', 'Saint Martin', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MG', 'Madagascar, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MH', 'Marshall Islands, Republic of the', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MK', 'Macedonia, The Former Yugoslav Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ML', 'Mali, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MM', 'Myanmar, Union of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MN', 'Mongolia', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MO', 'Macao, Special Administrative Region of China', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MP', 'Northern Mariana Islands, Commonwealth of the', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MQ', 'Martinique', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MR', 'Mauritania, Islamic Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MS', 'Montserrat', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MT', 'Malta, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MU', 'Mauritius, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MV', 'Maldives, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MW', 'Malawi, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MX', 'Mexico, United Mexican States', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MY', 'Malaysia', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('MZ', 'Mozambique, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NA', 'Namibia, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NC', 'New Caledonia', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NE', 'Niger, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NF', 'Norfolk Island', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NG', 'Nigeria, Federal Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NI', 'Nicaragua, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NL', 'Netherlands, Kingdom of the', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NO', 'Norway, Kingdom of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NP', 'Nepal, State of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NR', 'Nauru, Republic of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NU', 'Niue', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('NZ', 'New Zealand', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('OM', 'Oman, Sultanate of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PA', 'Panama, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PE', 'Peru, Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PF', 'French Polynesia', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PG', 'Papua New Guinea, Independent State of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PH', 'Philippines, Republic of the', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PK', 'Pakistan, Islamic Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PL', 'Poland, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PM', 'Saint Pierre and Miquelon', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PN', 'Pitcairn Islands', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PR', 'Puerto Rico, Commonwealth of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PS', 'Palestinian Territory, Occupied', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PT', 'Portugal, Portuguese Republic', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PW', 'Palau, Republic of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('PY', 'Paraguay, Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('QA', 'Qatar, State of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('RE', 'Reunion', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('RO', 'Romania', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('RS', 'Serbia, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('RU', 'Russian Federation', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('RW', 'Rwanda, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SA', 'Saudi Arabia, Kingdom of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SB', 'Solomon Islands', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SC', 'Seychelles, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SD', 'Sudan, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SE', 'Sweden, Kingdom of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SG', 'Singapore, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SH', 'Saint Helena', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SI', 'Slovenia, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SJ', 'Svalbard & Jan Mayen Islands', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SK', 'Slovakia (Slovak Republic)', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SL', 'Sierra Leone, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SM', 'San Marino, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SN', 'Senegal, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SO', 'Somalia, Somali Republic', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SR', 'Suriname, Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SS', 'South Sudan', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ST', 'Sao Tome and Principe, Democratic Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SV', 'El Salvador, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SX', 'Sint Maarten (Netherlands)', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SY', 'Syrian Arab Republic', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('SZ', 'Swaziland, Kingdom of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TC', 'Turks and Caicos Islands', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TD', 'Chad, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TF', 'French Southern Territories', 'AN');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TG', 'Togo, Togolese Republic', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TH', 'Thailand, Kingdom of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TJ', 'Tajikistan, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TK', 'Tokelau', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TL', 'Timor-Leste, Democratic Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TM', 'Turkmenistan', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TN', 'Tunisia, Tunisian Republic', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TO', 'Tonga, Kingdom of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TR', 'Turkey, Republic of', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TT', 'Trinidad and Tobago, Republic of', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TV', 'Tuvalu', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TW', 'Taiwan', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('TZ', 'Tanzania, United Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('UA', 'Ukraine', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('UG', 'Uganda, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('UM', 'United States Minor Outlying Islands', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('US', 'United States of America', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('UY', 'Uruguay, Eastern Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('UZ', 'Uzbekistan, Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('VA', 'Holy See (Vatican City State)', 'EU');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('VC', 'Saint Vincent and the Grenadines', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('VE', 'Venezuela, Bolivarian Republic of', 'SA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('VG', 'British Virgin Islands', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('VI', 'United States Virgin Islands', 'NA');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('VN', 'Vietnam, Socialist Republic of', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('VU', 'Vanuatu, Republic of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('WF', 'Wallis and Futuna', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('WS', 'Samoa, Independent State of', 'OC');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('YE', 'Yemen', 'AS');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('YT', 'Mayotte', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ZA', 'South Africa, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ZM', 'Zambia, Republic of', 'AF');
INSERT INTO serenity.tb_country (id, name, continent_id) VALUES ('ZW', 'Zimbabwe, Republic of', 'AF');

SET FOREIGN_KEY_CHECKS=1;